name: Hotfix CERTIFY PACKAGE

on:
  workflow_dispatch:
  #push:
   #branches: [ hotfix/production_bug_fixes ]
  #pull_request:
   # branches: [ hotfix/production_bug_fixes ]
  #schedule:
   # - cron:'0/5 * * * *' 
   
jobs:  

  #https://github.com/marketplace/actions/remote-ssh-commands
  copy-to-spaces:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/hotfix/production_bug_fixes'
    name: copy to spaces
    steps:       
      - name: artifacts uploading to spaces from Hotfix server. 
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/anudan/github
            ls -a
            #!/bin/bash
            TAG_NO_1=`cat release.json | cut -d "," -f2 | cut -d ":" -f2 | sed 's/"//g'`
            TAG_NO_2=`cat release.json | cut -d "," -f3 |cut -d ":" -f2 | sed 's/"//g' |sed 's/}//g'`
            BuildNo=$TAG_NO_1-HF-$TAG_NO_2
            SRC=dist/
            /home/anudan/github/s3cmd/s3cmd-2.0.1/s3cmd -r put dist s3://anudan-hotfix-artifacts-test/"$BuildNo"/;
            SRC=*.jar
            /home/anudan/github/s3cmd/s3cmd-2.0.1/s3cmd -r put $SRC s3://anudan-hotfix-artifacts-test/"$BuildNo"/;
            SRC=application.yaml
            /home/anudan/github/s3cmd/s3cmd-2.0.1/s3cmd -r put $SRC s3://anudan-hotfix-artifacts-test/"$BuildNo"/;
            SRC=release.json
            /home/anudan/github/s3cmd/s3cmd-2.0.1/s3cmd -r put $SRC s3://anudan-hotfix-artifacts-test/"$BuildNo"/;
          host: ${{ secrets.HOST_HOTFIX  }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}     

  Release-repo-checkout:
      runs-on: ubuntu-latest 
      if: github.ref == 'refs/heads/hotfix/production_bug_fixes'
      name: Release Repo Checkout
      steps: 
      - uses: actions/checkout@v2
        with:
          repository: anudan-org/release   
          token: ${{ secrets.MY_PAT }}
          ref: master
          #persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          #fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: set variables
        run: | 
             echo "major=`cat release.json | cut -d "," -f4 | cut -d ":" -f2 | sed 's/"//g' | sed 's/}//g'`" >> $GITHUB_ENV  
             echo "minor=`cat release.json | cut -d "," -f5 | cut -d ":" -f2 | sed 's/"//g' | sed 's/}//g'`" >> $GITHUB_ENV  
             echo "releaseCandidate=`cat release.json | cut -d "," -f1 | cut -d ":" -f2 | sed 's/"//g'`" >> $GITHUB_ENV 
             echo "productionRelease=`cat release.json | cut -d "," -f2 | cut -d ":" -f2 | sed 's/"//g'`" >> $GITHUB_ENV
             echo "hotFixRelease=`cat release.json | cut -d "," -f3 |cut -d ":" -f2 | sed 's/"//g' |sed 's/}//g'`" >> $GITHUB_ENV
      - name: release version creating for UAT
        run: | 
             echo '{"releaseCandidate":"${{ env.major}}.${{ env.minor }}.${{ env.releaseCandidate }}","productionRelease":"${{ env.major}}.${{ env.minor }}.${{ env.productionRelease }}","hotFixRelease":"${{ env.hotFixRelease }}"}' > release.json 
             ls -lrt    
      - name: uploading release.json artifact to github. 
        uses: actions/upload-artifact@v2
        with:
          name: Anudan-Release
          path: release.json
          retention-days: 1         
     
  Tag-Frontend-Master-Branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/hotfix/production_bug_fixes'
    needs: [Release-repo-checkout]
    name: Tag Frontend Master Branch
    steps:
    - name: check out anudan-app master
      uses: actions/checkout@master
      with:
          repository: anudan-org/anudan-app  
          token: ${{ secrets.MY_PAT }} 
          ref: hotfix/production_bug_fixes
    - name: Anudan Release artifact downloading from github.    
      uses: actions/download-artifact@v2
      with:
        name: Anudan-Release
    - name: Create local changes
      run: |
            pwd
            ls -lrt
    - name: Commit Tag
      run: |
          
          # retrieve branch name
          BRANCH_NAME=$(git branch | sed -n '/\* /s///p')

          # remove prefix release
          REGEXP_RELEASE="release\/"
          VERSION_BRANCH=$(echo "$BRANCH_NAME" | sed "s/$REGEXP_RELEASE//") 
          echo "Current version branch is $VERSION_BRANCH"
          TAG_NO_1=`cat release.json | cut -d "," -f2 | cut -d ":" -f2 | sed 's/"//g'`
          TAG_NO_2=`cat release.json | cut -d "," -f3 |cut -d ":" -f2 | sed 's/"//g' |sed 's/}//g'`
          echo $TAG_NO
          git config --local user.email "admin@anudan.org"
          git config --local user.name "${GITHUB_ACTOR}"
          git tag $TAG_NO_1-HF-$TAG_NO_2
          git push origin hotfix/production_bug_fixes $TAG_NO_1-HF-$TAG_NO_2  
        


  Tag-Backend-Master-Branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/hotfix/production_bug_fixes'
    needs: [Release-repo-checkout]
    name: Tag Backend Master Branch
    steps:
    - name: check out gms-service master
      uses: actions/checkout@master
      with:
          repository: anudan-org/gms-service 
          token: ${{ secrets.MY_PAT }} 
          ref: hotfix/production_bug_fixes

    - name: Anudan Release artifact downloading from github.    
      uses: actions/download-artifact@v2
      with:
        name: Anudan-Release
    - name: Create local changes
      run: |
            pwd
            ls -lrt
    - name: Commit Tag
      run: |
          
          # retrieve branch name
          BRANCH_NAME=$(git branch | sed -n '/\* /s///p')

          # remove prefix release
          REGEXP_RELEASE="release\/"
          VERSION_BRANCH=$(echo "$BRANCH_NAME" | sed "s/$REGEXP_RELEASE//") 
          echo "Current version branch is $VERSION_BRANCH"
          TAG_NO_1=`cat release.json | cut -d "," -f2 | cut -d ":" -f2 | sed 's/"//g'`
          TAG_NO_2=`cat release.json | cut -d "," -f3 |cut -d ":" -f2 | sed 's/"//g' |sed 's/}//g'`
          echo $TAG_NO
          git config --local user.email "admin@anudan.org"
          git config --local user.name "${GITHUB_ACTOR}"
          git tag $TAG_NO_1-HF-$TAG_NO_2 
          git push origin hotfix/production_bug_fixes $TAG_NO_1-HF-$TAG_NO_2   
         

  Notify-on-email:
    runs-on: ubuntu-latest
    if: always()
    needs: [copy-to-spaces, Release-repo-checkout, Tag-Frontend-Master-Branch,  Tag-Backend-Master-Branch]
    name: Notify Via Email
    steps:
      - name: Anudan Release artifact downloading from github.     
        uses: actions/download-artifact@v2
        with:
          name: Anudan-Release 

      - name: set env variable with bash expression 
        run:   |
         ls -lrt
         TAG_NO_1=`cat release.json | cut -d "," -f2 | cut -d ":" -f2 | sed 's/"//g'`
         TAG_NO_2=`cat release.json | cut -d "," -f3 |cut -d ":" -f2 | sed 's/"//g' |sed 's/}//g'`
         echo "Hotfix_Release=$TAG_NO_1-HF-$TAG_NO_2" >> $GITHUB_ENV
      - name: Send some mail
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.gmail.com
          port: ${{ secrets.SMTP_SERVER_PORT }}
          username: ${{ secrets.AUTH_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Hotfix Approved Application - CERTIFY PACKAGE Workflow Finished
          body: Organization Name/Repository - ${{github.repository}} 
           
                Changes done by - ${{ github.actor }}



                1. copy to spaces - ${{needs.copy-to-spaces.result}} 

                2. Release Repo Checkout - ${{needs.Release-repo-checkout.result}} 

                3. Tag Frontend Master Branch - ${{needs.Tag-Frontend-Master-Branch.result}}

                4. Tag Backend Master Branch - ${{needs.Tag-Backend-Master-Branch.result}}

                5. Anudan - Grant Management System â€º Hotfix Approved - ${{ env.Hotfix_Release }}
                 
          to: ${{ secrets.TO_ADDRESSES }} 
          from:   ${{ secrets.FROM_ADDRESS }}      

            