name: UAT Rlease Version

on:
  workflow_dispatch:
  #push:
   #branches: [ master ]
  #pull_request:
   # branches: [ master ]
  #schedule:
   # - cron:'0/5 * * * *' 
   
jobs:
  # this block of code will create UAT release version for UAT remote server. 
  UAT-Rlease-version:
      runs-on: ubuntu-latest 
      name: UAT Rlease version
      if: github.ref == 'refs/heads/master' 
      steps:
        - uses: actions/checkout@v2
          with:
            repository: anudan-org/release   
            token: ${{ secrets.MY_PAT }}
        - name: setup variable
          run: | 
             echo "major=`cat release.json | cut -d "," -f4 | cut -d ":" -f2 | sed 's/"//g' | sed 's/}//g'`" >> $GITHUB_ENV  
             echo "minor=`cat release.json | cut -d "," -f5 | cut -d ":" -f2 | sed 's/"//g' | sed 's/}//g'`" >> $GITHUB_ENV   
        - name: release version creating for UAT
          run: | 
             echo '{"releaseCandidate":"${{env.major}}.${{env.minor}}.${{ github.run_number }} UC"}' > UAT_release.json 
             ls -lrt
        - name: Commit files
          run: |
            git config --local user.email "admin@anudan.org"
            git config --local user.name "${GITHUB_ACTOR}"
            git add .
            git commit -m "UAT Release Version UAT R-${{env.major}}.${{env.minor}}.${{ github.run_number }} UC" 
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.MY_PAT }}
            repository: anudan-org/release 
            branch: master
             

                  
